from __future__ import annotations

from collections.abc import Sequence
from datetime import datetime
from typing import Protocol

from astrafeed.domain import Channel, CostEntry, Interest, Verdict


class Repository(Protocol):
    """Channel definitions, Interests and per-run processing state."""

    # --- definitions ---
    async def add_channel(self, channel: Channel) -> Channel: ...
    async def list_channels(self) -> list[Channel]: ...
    async def get_channel(self, channel_id: int) -> Channel | None: ...

    async def set_global_interests(self, interests: Sequence[Interest]) -> None: ...
    async def global_interests(self) -> list[Interest]: ...

    # --- processing state ---
    async def get_watermark(self, channel_id: int) -> datetime | None: ...
    async def set_watermark(self, channel_id: int, value: datetime) -> None: ...

    async def enqueue_report(self, verdict: Verdict) -> None: ...
    async def peek_report_queue(self) -> list[tuple[int, Verdict]]: ...
    async def ack_report(self, ids: Sequence[int]) -> None: ...

    # --- persistent dedup (issue 15) ---
    async def seen_signatures(self, signatures: set[str], since: datetime) -> set[str]: ...
    async def record_seen(self, signatures: set[str], when: datetime) -> None: ...

    # --- cost log ---
    async def log_cost(self, entry: CostEntry) -> None: ...
    async def total_cost(self) -> float: ...
