"""Preliminary agent gold for author-thesis extraction on the transfer sample.

Written from the posts and the already-published transfer labels, before any
extract or B-linker call. Old artifacts/reaction-subject/transfer/labels.jsonl
is not edited. A new extracted thesis_id is never scored against the old null
target_id; a mere author_thesis class match is not a specific link.

Regenerate:
    python3 docs/research/reaction_subject_thesis.py label
"""

from __future__ import annotations

# (thread_url, quote, kind, topic_role, origin, rank, disputed, note)
# origin=author is expected from the extractor. cited/event/promo are recorded
# so an extraction of those claims is an extra, not a hit.
# rank 1–3 are the ones the extractor should keep if it truncates; rank>=4 is overflow.
POST_THESES: list[tuple[str, str, str, str, str, int, bool, str]] = [
    (
        "https://t.me/CoinMetrika/4551",
        "После ювелирной медвежьей ловушки может продемонстрировать похожее и для быков, отправив BTC в сторону $70к и ETH в сторону $2к.",
        "forecast",
        "subject",
        "author",
        1,
        False,
        "конкретный встречный сценарий по ETH/BTC",
    ),
    (
        "https://t.me/CoinMetrika/4551",
        "на дневном графике BTC формируется медвежий div",
        "evaluation",
        "context",
        "author",
        2,
        False,
        "авторский ТА-вывод, не чужая цитата",
    ),
    (
        "https://t.me/CoinMetrika/4551",
        "Но пока рынок бычий, время есть",
        "evaluation",
        "context",
        "author",
        3,
        False,
        "бычья рамка поста; «Бычка это хорошо» бьёт сюда",
    ),
    (
        "https://t.me/CoinMetrika/4551",
        "бороться можно лишь не all inn позициями, оставляя себе гибкость для маневров",
        "advice",
        "context",
        "author",
        4,
        False,
        "четвёртый тезис: при обрезке до 3 не обязан быть извлечён",
    ),
    (
        "https://t.me/DeFi_learn/496",
        "доходность ваулта — это не только APY, но и вопрос контроля",
        "evaluation",
        "context",
        "author",
        1,
        True,
        "рамка автора вокруг чужого отчёта Xerberus",
    ),
    (
        "https://t.me/DeFi_learn/496",
        "Перед депозитом стоит проверить, кто и как меняет стратегию",
        "advice",
        "context",
        "author",
        2,
        False,
        "практический совет автора, не факт отчёта",
    ),
    (
        "https://t.me/Nat_Selection/7228",
        "$ETH looks like shit ☠️",
        "evaluation",
        "subject",
        "author",
        1,
        False,
        "единственный тезис поста",
    ),
    (
        "https://t.me/Nat_Selection/7237",
        "up to 3000$ $ETH",
        "forecast",
        "subject",
        "author",
        1,
        True,
        "короткий прогноз; может быть подписью к картинке",
    ),
    (
        "https://t.me/NewBitFuture/2259",
        "Статья немного напоминает питч для инвесторов, но тем не менее стоит признать способность Pendle адаптироваться под каждый нарратив рынка и планомерно совершенствовать свой протокол.",
        "evaluation",
        "unrelated",
        "author",
        1,
        False,
        "собственный вывод автора, не тезис Pendle",
    ),
    (
        "https://t.me/NewBitFuture/2259",
        "Главный тезис: доходность трёх главных волн цикла (стейблкоинов, токенизированных RWA и перпов) рано или поздно придёт на одну глубокую площадку, и это Pendle.",
        "forecast",
        "unrelated",
        "cited",
        0,
        False,
        "это тезис статьи Pendle Inevitable; извлекать как авторский нельзя",
    ),
    (
        "https://t.me/maxshitpostit/833",
        "fomo и торговля в ончейне становится в какой-то степени более важным, чем даже листинги",
        "evaluation",
        "context",
        "author",
        1,
        False,
        "",
    ),
    (
        "https://t.me/maxshitpostit/833",
        "тебе хватит просто @maestro и chart.zone",
        "advice",
        "subject",
        "author",
        2,
        True,
        "совет, рядом с рекламой fomo",
    ),
    (
        "https://t.me/maxshitpostit/833",
        "На завтра надо тебе 20-30 NFT коллекций",
        "advice",
        "subject",
        "author",
        3,
        True,
        "в старых метках эта фраза размечена как event",
    ),
    (
        "https://t.me/maxshitpostit/836",
        "99% из них - параша лютая, делай сам дальше свой due diligence",
        "evaluation",
        "subject",
        "author",
        1,
        False,
        "",
    ),
    (
        "https://t.me/maxshitpostit/836",
        "А я б лучше пошел в эфир и выбил бы либо Standard Reserve (еще 650 слотов из 1000 и 2 дня до запуска), либо Rare Firends от фаундера Doodles.",
        "advice",
        "context",
        "author",
        2,
        False,
        "",
    ),
    (
        "https://t.me/maxshitpostit/836",
        "Торговать NFT 16 числа на fomo",
        "advice",
        "context",
        "author",
        3,
        True,
        "совет / промо fomo",
    ),
    (
        "https://t.me/maxshitpostit/837",
        "не недооценивай силу колзов, их копиков и тезисов",
        "advice",
        "context",
        "author",
        1,
        True,
        "единственный явный совет; список адресов — не тезисы",
    ),
    (
        "https://t.me/maxshitpostit/840",
        "TLDR, почему буллиш:",
        "evaluation",
        "subject",
        "author",
        1,
        False,
        "рамка автора; дальше идут факты в её поддержку",
    ),
    (
        "https://t.me/maxshitpostit/840",
        "выходит интересная потенциальная ставка",
        "evaluation",
        "subject",
        "author",
        2,
        False,
        "",
    ),
    (
        "https://t.me/maxshitpostit/840",
        "спойлер - все хуево",
        "evaluation",
        "subject",
        "author",
        3,
        False,
        "оценка экосистемы, не самого ZEC",
    ),
    (
        "https://t.me/maxshitpostit/841",
        "Не думаю, что они смогут на что-то претендовать просто потому что",
        "evaluation",
        "subject",
        "author",
        1,
        False,
        "оценка Arc",
    ),
    (
        "https://t.me/maxshitpostit/841",
        "Их публичный отказ от мемов месяц назад говорит о том, что поддерживать весь этот движ они вряд ли будут",
        "evaluation",
        "subject",
        "author",
        2,
        False,
        "",
    ),
    (
        "https://t.me/maxshitpostit/841",
        "скорее всего щитки попампятся еще недельку, максимум две, а потом обратно вернемся в родную гавань",
        "forecast",
        "subject",
        "author",
        3,
        False,
        "",
    ),
    (
        "https://t.me/maxshitpostit/841",
        "как будто не ошибка сейчас вернуться на Робингуд и откупить то, что сильно скорректировалось",
        "advice",
        "unrelated",
        "author",
        4,
        False,
        "overflow",
    ),
    (
        "https://t.me/maxshitpostit/842",
        "апсайд по росту еще есть - как минимум у нас еще не было меты, когда мы все дружно летим в пирамидки",
        "evaluation",
        "context",
        "author",
        1,
        False,
        "",
    ),
    (
        "https://t.me/maxshitpostit/842",
        "я сам только в Стандарте сижу",
        "evaluation",
        "unrelated",
        "author",
        2,
        True,
        "личная позиция, не совет читателю",
    ),
    (
        "https://t.me/maxshitpostit/843",
        "кино кончилось досрочно, возвращаемся в родную гавань",
        "evaluation",
        "unrelated",
        "author",
        1,
        False,
        "про Arc/Robinhood, запрошенная тема ZEC",
    ),
    (
        "https://t.me/maxshitpostit/843",
        "я не очень поверил в эту историю, потому что это буквально тоже самое, что на Base сделали Surplus Intelligence",
        "evaluation",
        "unrelated",
        "author",
        2,
        False,
        "ORBIO",
    ),
    (
        "https://t.me/maxshitpostit/847",
        "Я лично ставку на стандард сделал, но я сделал еще на генезис минте",
        "evaluation",
        "unrelated",
        "author",
        1,
        False,
        "",
    ),
    (
        "https://t.me/maxshitpostit/847",
        "может он вообще сможет продаться Робингудам?",
        "forecast",
        "unrelated",
        "author",
        2,
        True,
        "вопрос-прогноз",
    ),
    (
        "https://t.me/maxshitpostit/847",
        "Одно дело - когда ты строишь понци, другое - прокачиваешь всю экосистему",
        "evaluation",
        "unrelated",
        "author",
        3,
        False,
        "",
    ),
    (
        "https://t.me/sellnotbuych/271",
        "Почему же я продолжаю работать от шорта?",
        "evaluation",
        "unrelated",
        "author",
        1,
        True,
        "заголовок аргумента; сам шорт нефти — позиция автора",
    ),
    (
        "https://t.me/sellnotbuych/271",
        "По золоту все еще остаюсь бычком, но уже в долгую",
        "evaluation",
        "unrelated",
        "author",
        2,
        False,
        "",
    ),
    (
        "https://t.me/sellnotbuych/271",
        "По крипте же все сейлы скипаю, ничего интересного не вижу",
        "advice",
        "context",
        "author",
        3,
        False,
        "",
    ),
    (
        "https://t.me/sellnotbuych/273",
        "Но главный секрет роста CC вообще не в коллекционерах",
        "evaluation",
        "unrelated",
        "author",
        1,
        False,
        "",
    ),
    (
        "https://t.me/sellnotbuych/273",
        "это чейн не про лудки, а про что-то на подобии Canton, только без непонятной подковерной игры инсайдеров",
        "evaluation",
        "subject",
        "author",
        2,
        True,
        "оценка Arc",
    ),
    (
        "https://t.me/sellnotbuych/273",
        "Собираюсь нести сюда очень много",
        "forecast",
        "unrelated",
        "author",
        3,
        False,
        "Dawn, не Arc",
    ),
    (
        "https://t.me/shtanga0x/1122",
        "Я рассматриваю занос в DJI",
        "advice",
        "unrelated",
        "author",
        1,
        True,
        "личная заявка; остальное ближе к промо A2DAO",
    ),
    (
        "https://t.me/tradeinvestAndCat/4137",
        "есть мысль актив в мэйнете тыкать нативно под будущее ввозможное что-то ( но каждый решает для себя сам)",
        "advice",
        "subject",
        "author",
        1,
        False,
        "",
    ),
    (
        "https://t.me/tradeinvestAndCat/4137",
        "говно минты в 1-2$ профита говно конечно но если цель активность нативно апнуть то  можно и тыкать",
        "advice",
        "context",
        "author",
        2,
        False,
        "про рх, не про Arc",
    ),
    (
        "https://t.me/tradeinvestAndCat/4147",
        "можно постов в х потыкать ( вроде мониторят )",
        "advice",
        "subject",
        "author",
        1,
        True,
        "слабый совет вокруг анонса минта",
    ),
    (
        "https://t.me/workIncrypts/12707",
        "Realgo — говно игра",
        "evaluation",
        "unrelated",
        "author",
        1,
        False,
        "пункт дайджеста",
    ),
    (
        "https://t.me/workIncrypts/12707",
        "popdex- перспективные перпы с 30кк инвеста",
        "evaluation",
        "unrelated",
        "author",
        2,
        False,
        "",
    ),
    (
        "https://t.me/workIncrypts/12707",
        "BreathOfEstova - еще пиксельная игра где бесплатно можно тыкать, выглядит прикольно",
        "evaluation",
        "unrelated",
        "author",
        3,
        False,
        "",
    ),
]

# Posts that were read and judged to have zero author theses (promo, question,
# timestamps, reported headline, news-only). Listed so extras can be scored.
EMPTY_POSTS = [
    "https://t.me/CoinMetrika/4550",
    "https://t.me/Nat_Selection/7230",
    "https://t.me/Nat_Selection/7235",
    "https://t.me/maxshitpostit/838",
    "https://t.me/maxshitpostit/845",
    "https://t.me/tradeinvestAndCat/4121",
    "https://t.me/workIncrypts/12745",
]

# (comment_id, expected_gold_id or None, linkable, basis_comment, basis_post, disputed, note)
# expected_gold_id names a POST_THESES quote via gold_id() below, not an extracted id.
COMMENT_LINKS: list[tuple[str, str | None, bool, str, str, bool, str]] = [
    (
        "eth|https://t.me/CoinMetrika/4551?comment=605943",
        "gold:CoinMetrika/4551:3",
        True,
        "Бычка это хорошо",
        "Но пока рынок бычий, время есть",
        True,
        "дальше вопрос про clusters/circuit — старая метка спорная",
    ),
    (
        "eth|https://t.me/CoinMetrika/4551?comment=605983",
        "gold:CoinMetrika/4551:2",
        True,
        "Что за медвежий div?",
        "на дневном графике BTC формируется медвежий div",
        True,
        "вопрос к авторскому ТА",
    ),
    (
        "eth|https://t.me/Nat_Selection/7228?comment=64615",
        "gold:Nat_Selection/7228:1",
        True,
        "Почему",
        "$ETH looks like shit ☠️",
        False,
        "",
    ),
    (
        "eth|https://t.me/Nat_Selection/7228?comment=64618",
        "gold:Nat_Selection/7228:1",
        True,
        "именно это аффтор и имеет ввиду (looks like shit)",
        "$ETH looks like shit ☠️",
        False,
        "",
    ),
    (
        "eth|https://t.me/Nat_Selection/7228?comment=64620",
        "gold:Nat_Selection/7228:1",
        True,
        "если торговать, то после того, как увидим реакцию на такой пинбар",
        "$ETH looks like shit ☠️",
        True,
        "TLDR к своему разбору, наследует цепочку",
    ),
    (
        "eth|https://t.me/Nat_Selection/7228?comment=64624",
        "gold:Nat_Selection/7228:1",
        True,
        "Shёрт",
        "$ETH looks like shit ☠️",
        False,
        "",
    ),
    (
        "eth|https://t.me/NewBitFuture/2259?comment=151360",
        None,
        False,
        "не растёт TVL",
        "Главный тезис: доходность трёх главных волн цикла",
        True,
        "спор с питчем Pendle, не с выводом автора про адаптацию; конкретной авторской связи нет",
    ),
    (
        "eth|https://t.me/NewBitFuture/2259?comment=151362",
        None,
        False,
        "Согласен... пилят много",
        "Главный тезис: доходность трёх главных волн цикла",
        True,
        "наследует 151360; тоже не авторский тезис",
    ),
    (
        "arc|https://t.me/maxshitpostit/836?comment=64298",
        "gold:maxshitpostit/836:1",
        True,
        "1% это Arclings?)",
        "99% из них - параша лютая",
        False,
        "",
    ),
    (
        "arc|https://t.me/maxshitpostit/837?comment=64315",
        "gold:maxshitpostit/837:1",
        True,
        "Я так пока раскидал, посмотрим",
        "не недооценивай силу колзов, их копиков и тезисов",
        True,
        "расклад по списку ставок; связь с советом про колзов не бесспорна",
    ),
    (
        "zec|https://t.me/maxshitpostit/840?comment=64693",
        "gold:maxshitpostit/840:1",
        True,
        "Конченая туфта это zec",
        "TLDR, почему буллиш:",
        True,
        "может быть оценка проекта, а не спор с буллиш-рамкой",
    ),
    (
        "arc|https://t.me/maxshitpostit/841?comment=64759",
        "gold:maxshitpostit/841:2",
        True,
        "просто удалили посты старые в твиттере",
        "Их публичный отказ от мемов месяц назад",
        True,
        "уточняет довод об отказе от мемов",
    ),
    (
        "eth|https://t.me/maxshitpostit/842?comment=64871",
        "gold:maxshitpostit/842:1",
        True,
        "есть вайб что когда я зайду всему придет пизда",
        "апсайд по росту еще есть",
        True,
        "ирония к мете пирамид",
    ),
    (
        "eth|https://t.me/maxshitpostit/842?comment=64872",
        "gold:maxshitpostit/842:2",
        True,
        "Мне только стандарт и нравится",
        "я сам только в Стандарте сижу",
        True,
        "ближе к личной позиции автора, чем к тезису про апсайд",
    ),
    (
        "eth|https://t.me/maxshitpostit/847?comment=65088",
        "gold:maxshitpostit/847:1",
        True,
        "ну тут плей на пару месяцев имхо",
        "Я лично ставку на стандард сделал",
        True,
        "предок без текста; оценка ставки автора",
    ),
    (
        "eth|https://t.me/maxshitpostit/847?comment=65098",
        "gold:maxshitpostit/847:3",
        True,
        "не как очередной токен Robinhood Chain, а как потенциальный инфраструктурный проект",
        "Одно дело - когда ты строишь понци, другое - прокачиваешь всю экосистему",
        True,
        "пересказ идеи автора про кэшфлоу/экосистему",
    ),
    (
        "arc|https://t.me/tradeinvestAndCat/4137?comment=230870",
        "gold:tradeinvestAndCat/4137:1",
        True,
        "Думаем",
        "есть мысль актив в мэйнете тыкать нативно",
        True,
        "короткое «думаем» к совету",
    ),
    (
        "arc|https://t.me/tradeinvestAndCat/4137?comment=230891",
        "gold:tradeinvestAndCat/4137:2",
        True,
        "Тоже подсел на эти говноминты на рх",
        "говно минты в 1-2$ профита говно конечно",
        True,
        "",
    ),
]


def gold_id(thread: str, rank: int) -> str:
    slug = thread.rstrip("/").split("t.me/")[-1]
    return f"gold:{slug}:{rank}"
